project:
  type: website
  output-dir: docs

website:
  title: "Jasper Cain"
  description: "Writing, projects, and ideas."

  sidebar:
    style: "docked"
    background: "light"
    search: false
    contents:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Me"
      - href: writing/index.qmd
        text: "Writing"
      - href: projects/index.qmd
        text: "Projects"

  page-footer:
    center: "© 2026 Jasper Cain"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: article
